FROM rockylinux/rockylinux:8

RUN yum install -y ruby libjpeg-turbo libpng libXrender fontconfig libXext cpio

WORKDIR /root/wkhtmltopdf_binary_gem
COPY . .

CMD /root/wkhtmltopdf_binary_gem/bin/wkhtmltopdf --version
