FROM centos:7

RUN yum -y groupinstall "Development Tools" 
RUN yum install -y ruby libjpeg-turbo libXrender fontconfig libXext zlib-devel openssl11-libs

RUN curl -L https://sourceforge.net/projects/libpng/files/libpng16/1.6.37/libpng-1.6.37.tar.gz -o libpng-1.6.37.tar.gz
RUN tar xvf libpng-1.6.37.tar.gz
RUN cd libpng-1.6.37/ && ./configure --prefix=/usr && make && make install

RUN curl -L https://ftp.openssl.org/source/openssl-1.1.1k.tar.gz -o openssl-1.1.1k.tar.gz
RUN tar -xzvf openssl-1.1.1k.tar.gz
RUN cd openssl-1.1.1k && ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic && make && make install

RUN ldconfig

WORKDIR /root/wkhtmltopdf_binary_gem
COPY . .

CMD /root/wkhtmltopdf_binary_gem/bin/wkhtmltopdf --version
