FROM debian:9

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y ruby libjpeg62-turbo libpng16-16 libxrender1 libfontconfig1 libxext6 curl

WORKDIR /root/wkhtmltopdf_binary_gem
COPY . .

CMD /root/wkhtmltopdf_binary_gem/bin/wkhtmltopdf --version
