FROM centos:6

RUN rm -f /etc/yum.repos.d/CentOS-Base.repo && \
    sed -i "s/enabled=0/enabled=1/g" /etc/yum.repos.d/CentOS-Vault.repo && \
    yum clean all && \
    yum update -y && \
    yum install -y ruby libjpeg-turbo libpng libXrender fontconfig libXext

WORKDIR /root/wkhtmltopdf_binary_gem
COPY . .

CMD /root/wkhtmltopdf_binary_gem/bin/wkhtmltopdf --version
